//constants for signup
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
//constants for login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
// constants for reset login and signup
export const RESET_AUTH_MESSAGE = "RESET_AUTH_MESSAGE";
//constants for logout
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
//constants for forgot password
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";

export const FORGOT_PASSWORD_RESET_REQUEST = "FORGOT_PASSWORD_RESET_REQUEST";
export const FORGOT_PASSWORD_RESET_SUCCESS = "FORGOT_PASSWORD_RESET_SUCCESS";
//constants for add to cart
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCES";
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR";

//constants for remove from cart
export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const REMOVE_FROM_CART_ERROR = "REMOVE_FROM_CART_ERROR";

//constants for reset password
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

//constatnts for getting user info
export const GET_PROFILE_INFO_REQUEST = "GET_PROFILE_INFO_REQUEST";
export const GET_PROFILE_INFO_SUCCESS = "GET_PROFILE_INFO_SUCCESS";
export const GET_PROFILE_INFO_ERROR = "GET_PROFILE_INFO_ERROR";

//constants for update profile info
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";

//constants for adding date of birth
export const ADD_DATE_OF_BIRTH_REQUEST = "ADD_DATE_OF_BIRTH_REQUEST";
export const ADD_DATE_OF_BIRTH_SUCCESS = "ADD_DATE_OF_BIRTH_SUCCESS";
export const ADD_DATE_OF_BIRTH_ERROR = "ADD_DATE_OF_BIRTH_ERROR";

//constants for shipping address
export const ADD_SHIPPING_ADDRESS_REQUEST = "ADD_SHIPPING_ADDRESS_REQUEST";
export const ADD_SHIPPING_ADDRESS_SUCCESS = "ADD_SHIPPING_ADDRESS_SUCCESS";
export const ADD_SHIPPING_ADDRESS_ERROR = "ADD_SHIPPING_ADDRESS_ERROR";

//constants for messages
export const SEND_MESSAGES_REQUEST = "SEND_MESSAGES_REQUEST";
export const SEND_MESSAGES_SUCCESS = "SEND_MESSAGES_SUCCESS";
export const SEND_MESSAGES_ERROR = "SEND_MESSAGES_ERROR";

//constants get all messages
export const GET_ALL_MESSAGES_REQUEST = "GET_ALL_MESSAGES_REQUEST";
export const GET_ALL_MESSAGES_SUCCESS = "GET_ALL_MESSAGES_SUCCESS";
export const GET_ALL_MESSAGES_ERROR = "GET_ALL_MESSAGE_ERROR";

//constants for stripe payment
export const ADDING_PAYMENT_METHOD_REQUEST = "ADDING_PAYMENT_METHOD_REQUEST";
export const ADDING_PAYMENT_METHOD_SUCCESS = "ADDING_PAYMENT_METHOD_SUCCESS";
export const ADDING_PAYMENT_METHOD_ERROR = "ADDING_PAYMENT_METHOD_ERROR";

//constants for getting all cards
export const GET_ALL_CARDS_REQUEST = "GET_ALL_CARDS_REQUEST";
export const GET_ALL_CARDS_SUCCESS = "GET_ALL_CARDS_SUCCESS";
export const GET_ALL_CARDS_ERROR = "GET_ALL_CARDS_ERROR";

//constants for getting all orders
export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST";
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_ORDERS_ERROR = "GET_ALL_ORDERS_ERROR";

//constants for message read request
export const MESSAGE_READ_STATUS_REQUEST = "MESSAGE_READ_STATUS_REQUEST";
export const MESSAGE_READ_STATUS_SUCCESS = "MESSAGE_READ_STATUS_SUCCESS";
export const MESSAGE_READ_STATUS_ERROR = "MESSAGE_READ_STATUS_ERROR";

//constants for payment
export const CHARGE_CUSTOMER_REQUEST = "CHARGE_CUSTOMER_REQUEST";
export const CHARGE_CUSTOMER_SUCCESS = "CHARGE_CUSTOMER_SUCCESS";
export const CHARGE_CUSTOMER_ERROR = "CHARGE_CUSTOMER_ERROR";

//constants for updating appointment status
export const UPDATE_APPOINTMENT_REQUEST = "UPDATE_APPOINTMENT_REQUEST";
export const UPDATE_APPOINTMENT_SUCCESS = "UPDATE_APPOINTMENT_SUCCESS";
export const UPDATE_APPOINTMENT_ERROR = "UPDATE_APPOINTMENT_ERROR";

//constants for saving gender
export const SAVE_GENDER_REQUEST = "SAAVE_GENDER_REQUEST";
export const SAVE_GENDER_SUCCESS = "SAVE_GENDER_SUCCESS";
export const SAVE_GENDER_ERROR = "SAVE_GENDER_ERROR";

//constants for uploading photo
export const UPLOAD_PHOTO_REQUEST = "UPLOAD_PHOTO_REQUEST";
export const UPLOAD_PHOTO_SUCCESS = "UPLOAD_PHOTO_SUCCESS";
export const UPLOAD_PHOTO_ERROR = "UPLOAD_PHOTO_ERROR";

//constants for saving consent
export const SAVE_CONSENT_REQUEST = "SAVE_CONSENT_REQUEST";
export const SAVE_CONSENT_SUCCESS = "SAVE_CONSENT_SUCCESS";
export const SAVE_CONSENT_ERROR = "SAVE_CONSENT_ERROR";

//constants for Fetching all questions
export const FETCH_ALL_QUESTIONS_REQUEST = "FETCH_ALL_QUESTIONS_REQUEST";
export const FETCH_ALL_QUESTIONS_SUCCESS = "FETCH_ALL_QUESTIONS_SUCCESS";
export const FETCH_ALL_QUESTIONS_ERROR = "FETCH_ALL_QUESTIONS_ERROR";

//constants for submitting answers
export const SUBMIT_ANSWERS_REQUEST = "SUBMIT_ANSWERS_REQUEST";
export const SUBMIT_ANSWERS_SUCCESS = "SUBMIT_ANSWERS_SUCCESS";
export const SUBMIT_ANSWERS_ERROR = "SUBMIT_ANSWERS_ERROR";

//constants fro creating user by Admin
export const CREATE_USER_BY_ADMIN_REQUEST = "CREATE_USER_BY_ADMIN_REQUEST";
export const CREATE_USER_BY_ADMIN_SUCCESS = "CREATE_USER_BY_ADMIN_SUCCESS";
export const CREATE_USER_BY_ADMIN_ERROR = "CREATE_USER_BY_ADMIN_ERROR";

//constants for getting customer details by Admin or Doctor
export const GET_CUSTOMER_DETAIL_REQUEST = "GET_CUSTOMER_DETAIL_REQUEST";
export const GET_CUSTOMER_DETAIL_SUCCESS = "GET_CUSTOMER_DETAIL_SUCCESS";
export const GET_CUSTOMER_DETAIL_ERROR = "GET_CUSTOMER_DETAIL_ERROR";

//constants for charging customer after approval
export const CHARGE_CUSTOMER_AFTER_APPROVAL_REQUEST =
  "CHARGE_CUSTOMER_AFTER_APPROVAL_REQUEST";
export const CHARGE_CUSTOMER_AFTER_APPROVAL_SUCCESS =
  "CHARGE_CUSTOMER_AFTER_APPROVAL_SUCCESS";
export const CHARGE_CUSTOMER_AFTER_APPROVAL_ERROR =
  "CHARGE_CUSTOMER_AFTER_APPROVAL_ERROR";

//constants for email send to doctor
export const EMAIL_SEND_DOCTOR_REQUEST = "EMAIL_SEND_DOCTOR_REQUEST";
export const EMAIL_SEND_DOCTOR_SUCCESS = "EMAIL_SEND_DOCTOR_SUCCESS";
export const EMAIL_SEND_DOCTOR_ERROR = "EMAIL_SEND_DOCTOR_ERROR";

//constants for email send to admin
export const EMAIL_SEND_ADMIN_REQUEST="EMAIL_SEND_ADMIN_REQUEST"
export const EMAIL_SEND_ADMIN_SUCCESS="EMAIL_SEND_ADMIN_SUCCESS"
export const EMAIL_SEND_ADMIN_ERROR="EMAIL_SEND_ADMIN_ERROR"

//constants for area wise user

export const AREA_USER_REQUEST="AREA_USER_REQUEST"
export const AREA_USER_SUCCESS="AREA_USER_SUCCESS"
export const AREA_USER_ERROR="AREA_USER_ERROR"

//constants for state doctor
export const FETCH_STATE_DOCTOR_REQUEST="FETCH_STATE_DOCTOR_REQUEST"
export const FETCH_STATE_DOCTOR_SUCCESS="FETCH_STATE_DOCTOR_SUCCESS"
export const FETCH_STATE_DOCTOR_ERROR="FETCH_STATE_DOCTOR_ERROR"

//constants for manage login 

export const LOGIN_FROM_START_REQUEST="LOGIN_FROM_START_REQUEST"
export const LOGIN_FROM_START_SUCCESS="LOGIN_FROM_START_SUCCESS"