//constants for signup
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
//constants for login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
// constants for reset login and signup
export const RESET_AUTH_MESSAGE = "RESET_AUTH_MESSAGE";
//constants for logout
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
//constants for forgot password
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";

export const FORGOT_PASSWORD_RESET_REQUEST = "FORGOT_PASSWORD_RESET_REQUEST";
export const FORGOT_PASSWORD_RESET_SUCCESS = "FORGOT_PASSWORD_RESET_SUCCESS";
//constants for add to cart
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCES";
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR";

//constants for remove from cart
export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const REMOVE_FROM_CART_ERROR = "REMOVE_FROM_CART_ERROR";

//constants for reset password
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

//constatnts for getting user info
export const GET_PROFILE_INFO_REQUEST = "GET_PROFILE_INFO_REQUEST";
export const GET_PROFILE_INFO_SUCCESS = "GET_PROFILE_INFO_SUCCESS";
export const GET_PROFILE_INFO_ERROR = "GET_PROFILE_INFO_ERROR";

//constants for update profile info
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";

//constants for adding date of birth
export const ADD_DATE_OF_BIRTH_REQUEST = "ADD_DATE_OF_BIRTH_REQUEST";
export const ADD_DATE_OF_BIRTH_SUCCESS = "ADD_DATE_OF_BIRTH_SUCCESS";
export const ADD_DATE_OF_BIRTH_ERROR = "ADD_DATE_OF_BIRTH_ERROR";

//constants for shipping address
export const ADD_SHIPPING_ADDRESS_REQUEST = "ADD_SHIPPING_ADDRESS_REQUEST";
export const ADD_SHIPPING_ADDRESS_SUCCESS = "ADD_SHIPPING_ADDRESS_SUCCESS";
export const ADD_SHIPPING_ADDRESS_ERROR = "ADD_SHIPPING_ADDRESS_ERROR";

//constants for messages
export const SEND_MESSAGES_REQUEST = "SEND_MESSAGES_REQUEST";
export const SEND_MESSAGES_SUCCESS = "SEND_MESSAGES_SUCCESS";
export const SEND_MESSAGES_ERROR = "SEND_MESSAGES_ERROR";

//constants get all messages
export const GET_ALL_MESSAGES_REQUEST = "GET_ALL_MESSAGES_REQUEST";
export const GET_ALL_MESSAGES_SUCCESS = "GET_ALL_MESSAGES_SUCCESS";
export const GET_ALL_MESSAGES_ERROR = "GET_ALL_MESSAGE_ERROR";

//constants for stripe payment
export const ADDING_PAYMENT_METHOD_REQUEST = "ADDING_PAYMENT_METHOD_REQUEST";
export const ADDING_PAYMENT_METHOD_SUCCESS = "ADDING_PAYMENT_METHOD_SUCCESS";
export const ADDING_PAYMENT_METHOD_ERROR = "ADDING_PAYMENT_METHOD_ERROR";

//constants for getting all orders
export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST";
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_ORDERS_ERROR = "GET_ALL_ORDERS_ERROR";
